server:
    port: 8084
zuul:
  ignoredPatterns:
    - /public/**
    - /widgets/**
  routes:
    oauth:
      path: /oauth/**
      url: http://localhost:5000/oauth
    snippet:
      path: /snippet/**
      url: http://localhost:5000/snippet
    html:
      path: /html/**
      url: http://localhost:5000/html
  Servlet30WrapperFilter:
    pre:
      disable:true